<template>
  <div class="ui container">
    <h2>Yammerer</h2>
    <div class="ui centered grid">
      <div class="ten wide column">
        <div class="ui threaded comments">
  
          <div class="ui text menu">
            <!--<div class="text item">Authoring as: {{autoGeneratedUserName}}</div>-->

            <div class="ui item">
            <a class="circular ui tiny image">
              <img v-bind:src="autoSelectedAvatar">
            </a>
            <div class="middle aligned content">
              <div class="header">
                {{autoGeneratedUserName}}
              </div>
            </div>
            </div>

            <div class="right menu">
              <div class="item">
                <div class="circular ui icon button" v-on:click.stop="toggleMessageForm()">
                   <i v-if="!showMessageForm" class="plus icon"></i>
                   <i v-else class="remove icon"></i>
                </div>
              </div>
            </div>
          </div>
          <div class="ui divider"></div>

          <form v-if="showMessageForm" class="ui reply form">
            <div class="field">
              <textarea v-model="newMessageContent" name="newMessageContent"></textarea>
            </div>
            <div class="ui primary labeled icon button" v-on:click.stop="addMessage()">
              <i class="icon edit"></i> Add Message 
            </div>
            <div class="ui divider hidden"></div>
          </form>
  
          <message v-for="message in messages"
                   :model="message"
                   :reply-as="autoGeneratedUserName"
                   :reply-as-avatar="autoSelectedAvatar"
                   :key="message.id"></message>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import helpers from '../helpers'
import Message from './Message'
import $ from 'jquery'
export default {
  name: 'channel',
  data () {
    return {
      // TODO - get this (messages array) json from a data store.
      messages: [{
        author: 'Mike Nolan',
        avatar: 'https://semantic-ui.com/images/avatar/small/matt.jpg',
        content: 'Gidday maaate!!',
        likes: 2,
        time: '2017-5-28 17:49:24',
        replies: [{
          author: 'Crazy Steve',
          avatar: 'https://semantic-ui.com/images/avatar/small/joe.jpg',
          content: 'Yeah nah yeah yeah nah.',
          likes: 0,
          replies: [],
          time: '2017-5-28 17:49:24'
        }]
      }],
      showMessageForm: false,
      newMessageContent: ''
    }
  },
  // computed props are methods which are evaluated ONCE, then cached for later.
  computed: {
    autoGeneratedUserName: function () {
      return helpers.getRandomUserName();
    },
    autoSelectedAvatar: function () {
      return helpers.getRandomAvatarUrl();
    }
  },
  // methods are evaluated every time they're invoked
  methods: {
    addMessage: function () {
      let messageForm = $('.ui.form');
      messageForm.form({
        fields: {
          newMessageContent: 'empty'
        }
      }).form('validate form');

      if (messageForm.form('is valid')) {
        // Add a message to the beginning of array, pass in the authoring details.
        this.messages.unshift(helpers.getNewMessage(this.autoGeneratedUserName, this.autoSelectedAvatar, this.newMessageContent));
        this.toggleMessageForm();
      }
    },
    toggleMessageForm: function () {
      this.showMessageForm = !this.showMessageForm;
      this.newMessageContent = '';
    }
  },
  components: {
    'message': Message
  }
}
</script>

<style>
h1,
h2 {
  font-weight: normal;
}

ul {
  list-style-type: none;
  padding: 0;
}

li {
  display: inline-block;
  margin: 0 10px;
}

a {
  color: #42b983;
}
</style>
